### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by justastranger** [webmilio/WebmiliosCommons#1]
```
[19:45:47] [.NET ThreadPool Worker/INFO] [tML]: Initializing: WebmilioCommons v0.3.7
[19:45:47] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass45_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 114
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[19:45:47] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading WebmilioCommons
The mod(s) have been automatically disabled.
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebmilioCommons.ModTagsSystem.get_SupportedTags() in C:\Users\there\Documents\My Games\Terraria\ModLoader\Beta\Mod Sources\WebmilioCommons\Mod\ModTagsSystem.cs:line 84
   at WebmilioCommons.ModTagsSystem.AddModTag(ValueTuple`2[] tags) in C:\Users\there\Documents\My Games\Terraria\ModLoader\Beta\Mod Sources\WebmilioCommons\Mod\ModTagsSystem.cs:line 66
   at WebmilioCommons.ModTagsSystem.Load() in C:\Users\there\Documents\My Games\Terraria\ModLoader\Beta\Mod Sources\WebmilioCommons\Mod\ModTagsSystem.cs:line 43
   at Terraria.ModLoader.ModType.Terraria.ModLoader.ILoadable.Load(Mod mod) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModType.cs:line 26
   at Terraria.ModLoader.Mod.AddContent(ILoadable instance) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Mod.cs:line 137
   at Terraria.ModLoader.Mod.Autoload() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 48
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 306
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
[19:45:47] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: WebmilioCommons
```

Error occurs even when it's the only mod enabled.

tModLoader version is `1.4.3.2+0.12-1.4-Alpha-3192afa8df3670f9af0324da58a932de73be2b21-5249441319801399378`

Full log can be found [here](https://pastebin.com/zLE4iKEn).

**Comment by webmilio** [comment]
Thanks for the report. I've been trying to replicate this but I can't seem to get it to crash...

Is this bug still happening on your end?
